### ISSUE TITLE
Push 0.5.1 to RubyGems.org

### ISSUE THREAD

**Issue by nbibler** [hashrocket/mousetrap#2]
I saw that mousetrap 0.5.1 was stamped a couple days back, but there's no entry for it yet on RubyGems.org... care to push it up?  :-D

**Comment by l4rk** [comment]
Thanks for the note. Yeah, I'm getting there I promise, I just have to figure out Hashrocket's password for rubygems.org. One-a my co-workers have it but they won't tell me. :)

**Comment by jwworth** [comment]
Closing this issue; Mousetrap has been superseded by the official client: https://github.com/expectedbehavior/cheddargetter_client_ruby.
